exercism/swift

grade-school/GradeSchoolTest.swift
nucleotide-count/NucleotideCountTest.swift
robot-name/RobotNameTest.swift
sum-of-multiples/SumOfMultiplesTest.swift
sum-of-multiples/example.swift

Previous tests forced the use of only classes. Now reference and values
types can be tested

changed 3 tests to also work with structs

---

bin/fetch-configlet
config.json
gigasecond/GigasecondTest.swift
gigasecond/example.swift
grade-school/GradeSchoolTest.swift
meetup/MeetupTest.swift
meetup/example.swift
nucleotide-count/NucleotideCountTest.swift
robot-name/RobotNameTest.swift
scrabble-score/ScrabbleScoreTest.swift
scrabble-score/example.swift
space-age/SpaceAgeTest.swift
space-age/example.swift
sum-of-multiples/SumOfMultiplesTest.swift
sum-of-multiples/example.swift
triangle/TriangleTest.swift
triangle/example.swift
twelve-days/TwelveDaysTest.swift
twelve-days/example.swift

@hankturowski  Could you take at look at these five problems I implemented? 
Any feedback on the test is appreciated as I would like to continue with the rest on the list. 
I made that list comparing csharp's list and swift. ( I thought those tracks would be similar ).
Thanks
TODO:

10 problems Added

---

meetup/MeetupTest.swift
meetup/example.swift

https://github.com/exercism/xswift/issues/32

added Meetp edge cases

---

meetup/MeetupTest.swift
meetup/example.swift

Revert "added Meetup edge cases"

---

accumulate/AccumulateTest.swift
acronym/example.swift
anagram/example.swift
binary/example.swift
bob/example.swift
config.json
crypto-square/example.swift
gigasecond/GigasecondTest.swift
gigasecond/example.swift
grains/GrainsTest.swift
grains/example.swift
meetup/MeetupTest.swift
meetup/example.swift
perfect-numbers/example.swift
phone-number/example.swift
prime-factors/example.swift
robot-name/RobotNameTest.swift
robot-name/example.swift
simple-cipher/example.swift
strain/example.swift

https://github.com/exercism/xswift/issues/40

Swift 1.2 update

---

sum-of-multiples/SumOfMultiplesTest.swift

https://github.com/exercism/exercism.io/issues/2341

update sum of multiples

---

config.json

Bob is currently a roadblock for many users. Moving it down the list.

Moving bob down the list of exercises

---

.travis.yml
xcodeProject/xSwift.xcodeproj/xcshareddata/xcschemes/xSwiftTests.xcscheme

https://github.com/exercism/xswift/issues/63

Travis integration enabled

---

gigasecond/GigasecondExample.swift
gigasecond/GigasecondTest.swift
meetup/MeetupExample.swift
meetup/MeetupTest.swift
wordy/WordyExample.swift

https://github.com/exercism/xswift/issues/54
Gigasecond
Meetup
Wordy

removed foundation requirement

---

meetup/MeetupExample.swift
meetup/MeetupTest.swift
tournament/TournamentExample.swift
tournament/TournamentTest.swift

Fixing typo also
https://github.com/exercism/xswift/pull/70/

update Meetup & Tournament favoring Accessor methods 

---

allergies/AllergiesExample.swift
allergies/AllergiesTest.swift

Added Patient requirement and capitalized the various allergens to
match Swift enum styling.

Updated Allergies to use swift enum

---

config.json
custom-set/CustomSetExample.swift
custom-set/CustomSetTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

https://github.com/exercism/xswift/pull/76

Add CustomSet

---

sum-of-multiples/SumOfMultiplesTest.swift

Closes https://github.com/exercism/todo/issues/63.

Add missing sum of multiples test

---

config.json
nth-prime/NthPrimeExample.swift
nth-prime/NthPrimeTest.swift
xcodeProject/xSwift Tests/NthPrimeExample.swift
xcodeProject/xSwift Tests/NthPrimeTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

Add Nth Prime exercise

---

grade-school/GradeSchoolExample.swift
grade-school/GradeSchoolTest.swift

https://github.com/exercism/xswift/pull/83

added workarounds to xctest

---

grade-school/GradeSchoolExample.swift
grade-school/GradeSchoolTest.swift

https://github.com/exercism/xswift/pull/83

update test to work with Sets

---

config.json
kindergarten-garden/KindergartenGardenExample.swift
kindergarten-garden/KindergartenGardenTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

Add Kindergarten Garden exercise

Add Kindergarten Garden

---

config.json
robot-simulator/RobotSimulatorExample.swift
robot-simulator/RobotSimulatorTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

Robot Simulator

---

robot-simulator/RobotSimulatorTest.swift

https://github.com/exercism/xswift/pull/92

removed Tight Coupling of the Enums used

---

config.json
queen-attack/QueenAttackExample.swift
queen-attack/QueenAttackTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

Add Queen Attack

---

config.json
exercises/binary-search-tree/BinarySearchTreeExample.swift
exercises/binary-search-tree/BinarySearchTreeTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

@masters3d I don't believe a solution is currently possible with structs (I get an error that `Recursive value type BinarySearchTree<T> is not allowed` when I try), but I'm using `var` instead of `let` just in case. 
Any thoughts on that?

Add Binary Search Tree exercise

---

exercises/triangle/TriangleExample.swift
exercises/triangle/TriangleTest.swift

https://github.com/exercism/xswift/issues/104

update isosceles test

---

config.json
exercises/house/HouseExample.swift
exercises/house/HouseTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

@masters3d Wish there was a better multi-line string syntax. `¯\_(ツ)_/¯`

Add House exercise

---

config.json
exercises/minesweeper/MinesweeperExample.swift
exercises/minesweeper/MinesweeperTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

@masters3d Are you ok including `Foundation` for this one? Otherwise the border validation will be trickier.

Add Minesweeper exercise

---

config.json
exercises/ocr-numbers/OcrNumbersExample.swift
exercises/ocr-numbers/OcrNumbersTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

@masters3d I've attempted to improve on the Ruby version by validating the input has a correct number of lines and columns.

Add OCR Numbers exercise

---

config.json
exercises/saddle-points/SaddlePointsExample.swift
exercises/saddle-points/SaddlePointsTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

@masters3d This is the last of the 'Suggested List of Problems post Swift 2.0'.

Add Saddle Points exercise

---

config.json
exercises/dominoes/DominoesExample.swift
exercises/dominoes/DominoesTest.swift
exercises/poker/PokerTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

https://github.com/exercism/xswift/issues/118

added Domino Chain

---

exercises/palindrome-products/PalindromeProductsExample.swift
exercises/palindrome-products/PalindromeProductsTest.swift

Cleaned up of test cases to be singular
https://github.com/exercism/xswift/issues/124

performance update to Palindrome example

---

exercises/palindrome-products/PalindromeProductsExample.swift
exercises/palindrome-products/PalindromeProductsTest.swift

- replaced arrays in forever to unordered sets
- added multi-treading to the example code to speed up overall tests

update to Palindrome from Array to Unordered Sets

---

exercises/binary/BinaryTest.swift
exercises/bob/BobTest.swift
exercises/difference-of-squares/DifferenceOfSquaresTest.swift
exercises/hamming/HammingTest.swift
exercises/nucleotide-count/NucleotideCountTest.swift
exercises/secret-handshake/SecretHandshakeTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

Seemed like `SomethingTest` and SomethingTest.swift were the most popular, so I went with those. While I was at it, I also sorted the exercises in the Project navigator so that it was easier to find things.

Normalize test class and filenames

---

exercises/gigasecond/GigasecondTest.swift

sync up with
https://github.com/exercism/xruby/blob/master/exercises/gigasecond/gigasecond_test.rb

added two cases

---

.travis.yml
config.json
exercises/bowling/BowlingExample.swift
exercises/bowling/BowlingTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

@masters3d Trying to DRY out the logic for testing errors thrown with `assertErrorThrown`. Let me know what you think.

Add Bowling exercise

---

exercises/space-age/SpaceAgeTest.swift

Working on this exercise, I had a difference in one decimal. And I realized that would be better to replace all those `XCTAssertTrue` with `XCTAssertEqual` in order to get a better feedback.
Please, have a look and let me know.
Thanks!

Change XCTAssertTrue with XCTAssertEqual

---

exercises/space-age/SpaceAgeTest.swift

Reverts exercism/xswift#173
This is causing merger conflict with master because they are the same change.

Revert "Change XCTAssertTrue with XCTAssertEqual"

---

config.json
exercises/run-length-encoding/RunLengthEncodingExample.swift
exercises/run-length-encoding/RunLengthEncodingTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

Add Run Length Encoding exercise

---

config.json

This addresses issue #170
https://github.com/exercism/xswift/issues/170

Update config.json to new specification

---

docs/LEARNING.md

Add swifteducation.github.io to LEARNING resources

---

config.json

follow up to https://github.com/exercism/xswift/pull/185
closes https://github.com/exercism/xswift/issues/170
```python
import json
import urllib2
swiftList = json.load(urllib2.urlopen('https://raw.githubusercontent.com/exercism/xswift/master/config.json'))
fsharpList = json.load(urllib2.urlopen('https://raw.githubusercontent.com/exercism/xfsharp/master/config.json'))
#swift Problems
swiftProblems = swiftList ['problems']
fsharpExercises = fsharpList ['exercises']
swiftExercises = []
for each in fsharpExercises:
if each['slug'] in swiftProblems:
swiftExercises.append(each)
print (json.dumps(swiftExercises, sort_keys=True, indent=4))
```

update config with fsharp's ordering

---

config.json
exercises/pangram/PangramExample.swift
exercises/pangram/PangramTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

Includes Foundation in order to strip diacritics from String. The last exercise could be removed if this is not desirable.

Add Pangram exercise

---

exercises/palindrome-products/PalindromeProductsExample.swift

Resolves #188 
* (Hopefully) fixes multi-threading crash in PalindromeProducts tests.
* Simplify the method for reversing a String
* Minor clean-up

Clean up PalindromeProducts

---

exercises/palindrome-products/PalindromeProductsExample.swift

Resolves #188
cc https://github.com/exercism/xswift/pull/198

fix random data race

---

Dangerfile

https://github.com/exercism/xswift/pull/200

update danger to warn on premature PR merge

---

config.json
exercises/isogram/IsogramExample.swift
exercises/isogram/IsogramTest.swift
xcodeProject/xSwift.xcodeproj/project.pbxproj

* Add Isogram exercise
(Foundation is required to use `CharacterSet`)

Add Isogram exercise

---

docs/TESTS.md

I missed several typos in the last commit, and a couple of them, bad filenames, could have lead people astray. This fixes them.

Fixed Several Typos

---

README.md

Update README.md with Link and Year 

---

exercises/grade-school/Tests/GradeSchoolTests/GradeSchoolTests.swift

This should help test across Any Collection that contains strings. 
close #258

Added generic XCTest Helper

---

.swiftlint.yml
.travis.yml
Dangerfile
Package.swift
exercises/accumulate/Tests/AccumulateTests/AccumulateTests.swift
exercises/acronym/Sources/AcronymExample.swift
exercises/bob/Sources/BobExample.swift
exercises/crypto-square/Sources/CryptoSquareExample.swift
exercises/custom-set/Sources/CustomSetExample.swift
exercises/dominoes/Sources/DominoesExample.swift
exercises/flatten-array/Sources/FlattenArrayExample.swift
exercises/gigasecond/Sources/GigasecondExample.swift
exercises/grains/Sources/GrainsExample.swift
exercises/luhn/Sources/LuhnExample.swift
exercises/meetup/Sources/MeetupExample.swift
exercises/ocr-numbers/Sources/OcrNumbersExample.swift
exercises/octal/Sources/OctalExample.swift
exercises/perfect-numbers/Sources/PerfectNumbersExample.swift
exercises/pig-latin/Sources/PigLatinExample.swift
exercises/poker/Sources/PokerExample.swift
exercises/pythagorean-triplet/Sources/PythagoreanTripletExample.swift
exercises/pythagorean-triplet/Tests/PythagoreanTripletTests/PythagoreanTripletTests.swift
exercises/secret-handshake/Sources/SecretHandshakeExample.swift
exercises/series/Sources/SeriesExample.swift
exercises/sieve/Sources/SieveExample.swift
exercises/strain/Tests/StrainTests/StrainTests.swift
exercises/tournament/Sources/TournamentExample.swift
exercises/word-count/Sources/WordCountExample.swift
exercises/wordy/Sources/WordyExample.swift

this fixes the closure spacing inconsistencies

Linter update fix

---

.gitignore
.swiftlint.yml
exercises/kindergarten-garden/Sources/KindergartenGardenExample.swift
exercises/kindergarten-garden/Tests/KindergartenGardenTests/KindergartenGardenTests.swift
exercises/meetup/Sources/MeetupExample.swift
exercises/poker/Sources/PokerExample.swift
exercises/robot-simulator/Sources/RobotSimulatorExample.swift
exercises/robot-simulator/Tests/RobotSimulatorTests/RobotSimulatorTests.swift

This fixes some of the new lint rules which cause errors

Fix Lint Errors

---

exercises/bob/Sources/BobExample.swift
exercises/bob/Tests/BobTests/BobTests.swift

Here's a first shot at fixing issue #255 and my first PR for exercism. Please let me know if you need me to make any additional changes. Thanks!

Fix issue #255

---

Dangerfile

Bot to report lint errors as warnings.

Lint error as CI warning

---

.travis.yml
Dangerfile

removing x from name for ci

---

exercises/acronym/Sources/AcronymExample.swift
exercises/crypto-square/Sources/CryptoSquareExample.swift
exercises/custom-set/Sources/CustomSetExample.swift
exercises/hamming/Sources/HammingExample.swift
exercises/nth-prime/Sources/NthPrimeExample.swift
exercises/poker/Sources/PokerExample.swift
exercises/pythagorean-triplet/Sources/PythagoreanTripletExample.swift
exercises/pythagorean-triplet/Tests/PythagoreanTripletTests/PythagoreanTripletTests.swift
exercises/rna-transcription/Sources/RnaTranscriptionExample.swift
exercises/rna-transcription/Tests/RnaTranscriptionTests/RnaTranscriptionTests.swift
exercises/secret-handshake/Sources/SecretHandshakeExample.swift
exercises/series/Sources/SeriesExample.swift
exercises/sum-of-multiples/Sources/SumOfMultiplesExample.swift
exercises/triangle/Sources/TriangleExample.swift
exercises/word-count/Sources/WordCountExample.swift

Env: Xcode 9b2 on Sierra 10.12.5
Just fixing a number of warnings issued by the bots.

Warnings fix

---

exercises/custom-set/Sources/CustomSetExample.swift
exercises/palindrome-products/Sources/PalindromeProductsExample.swift
exercises/poker/Sources/PokerExample.swift
exercises/secret-handshake/Sources/SecretHandshakeExample.swift
exercises/sum-of-multiples/Sources/SumOfMultiplesExample.swift

Added a few more fixings for various linting warnings that missed the 1st pass

Fixed a few more linting warnings

---

exercises/poker/Sources/PokerExample.swift
exercises/scrabble-score/Tests/ScrabbleScoreTests/ScrabbleScoreTests.swift

This is an offered solution for #268 
edit:
closes #268

Scrabble score test naming fix

---

config.json

https://github.com/exercism/swift/issues/292

update rotate cipher

---

Package.swift
exercises/atbash-cipher/Sources/AtbashExample.swift
exercises/bracket-push/Sources/BracketPushExample.swift
exercises/dominoes/Sources/DominoesExample.swift
exercises/grains/Tests/GrainsTests/GrainsTests.swift
exercises/kindergarten-garden/Sources/KindergartenGardenExample.swift
exercises/meetup/Sources/MeetupExample.swift
exercises/nucleotide-count/Sources/NucleotideCountExample.swift
exercises/poker/Sources/PokerExample.swift
exercises/rna-transcription/Sources/RnaTranscriptionExample.swift
exercises/rotational-cipher/Sources/RotationalCipherExample.swift

* Fixes most of the SwiftLint warnings

Fix warnings

---

config.json
exercises/collatz-conjecture/Package.swift
exercises/collatz-conjecture/README.md
exercises/collatz-conjecture/Sources/CollatzConjecture.swift
exercises/collatz-conjecture/Sources/CollatzConjectureExample.swift
exercises/collatz-conjecture/Tests/CollatzConjectureTests/CollatzConjectureTests.swift
exercises/collatz-conjecture/Tests/LinuxMain.swift

* Add the Collatz Conjecture exercise in Swift

Add Collatz Conjecture exercise

---

config.json
exercises/diamond/Package.swift
exercises/diamond/README.md
exercises/diamond/Sources/Diamond.swift
exercises/diamond/Sources/DiamondExample.swift
exercises/diamond/Tests/DiamondTests/DiamondTests.swift
exercises/diamond/Tests/LinuxMain.swift

Add Diamond exercise

---

.travis.yml

Fix swift 4 docker

---

config.json
exercises/isbn-verifier/Package.swift
exercises/isbn-verifier/README.md
exercises/isbn-verifier/Sources/IsbnVerifier.swift
exercises/isbn-verifier/Sources/IsbnVerifierExample.swift
exercises/isbn-verifier/Tests/IsbnVerifierTests/IsbnVerifierTests.swift
exercises/isbn-verifier/Tests/LinuxMain.swift

* Add ISBN Verifier exercise in Swift

Add ISBN Verifier exercise

---

config.json
exercises/two-fer/Package.swift
exercises/two-fer/README.md
exercises/two-fer/Sources/TwoFer.swift
exercises/two-fer/Sources/TwoFerExample.swift
exercises/two-fer/Tests/LinuxMain.swift
exercises/two-fer/Tests/TwoFerTests/TwoFerTests.swift

* Add TwoFer exercise in Swift

Add TwoFer exercise

---

config.json
exercises/protein-translation/Package.swift
exercises/protein-translation/README.md
exercises/protein-translation/Sources/ProteinTranslation.swift
exercises/protein-translation/Sources/ProteinTranslationExample.swift
exercises/protein-translation/Tests/LinuxMain.swift
exercises/protein-translation/Tests/ProteinTranslationTests/ProteinTranslationTests.swift

* Add Protein Translation in Swift

Add Protein Translation exercise

---

config.json
exercises/list-ops/Package.swift
exercises/list-ops/README.md
exercises/list-ops/Sources/ListOps.swift
exercises/list-ops/Sources/ListOpsExample.swift
exercises/list-ops/Tests/LinuxMain.swift
exercises/list-ops/Tests/ListOpsTests/ListOpsTests.swift

* Add List Ops exercise in Swift

Add List Ops exercise

---

.travis.yml
circle.yml

- Steps to remove travisCI mac

moved danger and macOS to circle

---

circle.yml

https://github.com/exercism/swift/pull/317

try to fix circle format

---

circle.yml

Don't fail build on danger errors

 Don't fail build on non zero exit codes

---

config.json
exercises/circular-buffer/.gitignore
exercises/circular-buffer/Package.swift
exercises/circular-buffer/README.md
exercises/circular-buffer/Sources/CircularBuffer.swift
exercises/circular-buffer/Sources/CircularBufferExample.swift
exercises/circular-buffer/Tests/CircularBufferTests/CircularBufferTests.swift
exercises/circular-buffer/Tests/LinuxMain.swift

* Add Circular Buffer exercise in Swift (uses generics)

Add Circular Buffer exercise

---

config.json
exercises/scale-generator/Package.swift
exercises/scale-generator/README.md
exercises/scale-generator/Sources/ScaleGenerator.swift
exercises/scale-generator/Sources/ScaleGeneratorExample.swift
exercises/scale-generator/Tests/LinuxMain.swift
exercises/scale-generator/Tests/ScaleGeneratorTests/ScaleGeneratorTests.swift

* Add Scale Generator exercise in Swift

Add Scale Generator exercise

---

circle.yml

Update circle.yml with xcode 9, 9.1 and 9.2

Update circle.yml with xcode 9, 9.1 and 9.2

---

.travis.yml

circle ci doesn't have support yet

travis xcode9.3beta

---

.travis.yml
circle.yml

added 9.3 xcode beta

---

config.json
exercises/complex-numbers/.gitignore
exercises/complex-numbers/Package.swift
exercises/complex-numbers/README.md
exercises/complex-numbers/Sources/ComplexNumbers.swift
exercises/complex-numbers/Sources/ComplexNumbersExample.swift
exercises/complex-numbers/Tests/ComplexNumbersTests/ComplexNumbersTests.swift
exercises/complex-numbers/Tests/LinuxMain.swift

Implemented the complex numbers exercise in Swift.

Add Complex Numbers exercise

---

exercises/isbn-verifier/Tests/IsbnVerifierTests/IsbnVerifierTests.swift

I completed the test cases with an empty string test, as one of the previous submitters was complaining about it.

New testCase added

---

config.json

added blurb

---

exercises/rna-transcription/Sources/RnaTranscriptionExample.swift
exercises/rna-transcription/Tests/RnaTranscriptionTests/RnaTranscriptionTests.swift

Solution to the problem described here https://github.com/exercism/swift/issues/356

Improvements to Rna Transcript Tests

---

xswift-test-spm

Fix --chdir/-C deprecation warning

---

Package.swift
circle.yml
exercises/custom-set/Sources/CustomSet/CustomSetExample.swift
exercises/isbn-verifier/Tests/IsbnVerifierTests/IsbnVerifierTests.swift
exercises/phone-number/Sources/PhoneNumber/PhoneNumberExample.swift
exercises/poker/Sources/Poker/PokerExample.swift
exercises/proverb/Tests/ProverbTests/ProverbTests.swift

The existing commands doesn't try to install swiftlint if it's not already installed, causing linting to fail.

Fix swiftlint not running on circle CI

---

exercises/hello-world/.meta/description.md
exercises/hello-world/.meta/hints.md
exercises/hello-world/README.md

The current exercise description for hello-world is incomplete. This is an attempt to improve the description and provide more details. 
- Add `description.md`, `hints.md` and `.meta` folder for hello-world.
- Generate and update `README.md`.

Fix for exercise description for hello-world

---

exercises/hamming/Sources/Hamming/HammingExample.swift

The hamming exercise is tagged with filtering. The example solution should use swift features and filtering to demonstrate this.

Update example solution for hamming distance demonstrating filtering.

---

exercises/tournament/Sources/Tournament/TournamentExample.swift
exercises/tournament/Tests/TournamentTests/TournamentTests.swift

* Bring tests in line with latest specs
* Make use of multi-line string literals for readability
* Clean up example

Revise Tournament exercise

---

circle.yml

Testing https://github.com/exercism/exercism/issues/4726
https://circleci.com/docs/2.0/testing-ios/

Update circle.yml for xcode 10.1

---

.gitignore
config/maintainers.json

Adding myself to the swift maintainers.json per @ErikSchierboom. Also added .swiftpm directory to the swift .gitignore.

Add wneumann to swift maintainers list

---

exercises/concept/bomb-defuser/.meta/config.json
exercises/concept/custom-signs/.meta/config.json
exercises/concept/freelancer-rates/.meta/config.json
exercises/concept/high-score-board/.meta/config.json
exercises/concept/lasagna-master/.meta/config.json
exercises/concept/lasagna/.meta/config.json
exercises/concept/log-lines/.meta/config.json
exercises/concept/magician-in-training/.meta/config.json
exercises/concept/master-mixologist/.meta/config.json
exercises/concept/pizza-slices/.meta/config.json
exercises/concept/poetry-club/.meta/config.json
exercises/concept/santas-helper/.meta/config.json
exercises/concept/secret-agent/.meta/config.json
exercises/concept/vehicle-purchase/.meta/config.json
exercises/concept/windowing-system/.meta/config.json

The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26

🤖 Flatten authors and contributors in .meta/config.json files

---

config.json

Closes https://github.com/exercism/swift/issues/444

Fix bomb-defuser exercise name

---

config.json

This PR adds some missing entries to the `concepts` array in the `config.json` file.

Fix concept linting

---

exercises/concept/vehicle-purchase/.docs/instructions.md

`help you help you` has been changed to `help you`

Remove redundant wording from instructions.md

---

exercises/concept/windowing-system/.docs/instructions.md

This adds a missing colon in the sample output.

Have sample match expected output in tests

---

exercises/practice/rna-transcription/Sources/RnaTranscription/RnaTranscription.swift

This will make it easier to understand this exercise.

Update to fit other exercises

---

exercises/concept/vehicle-purchase/.docs/instructions.md

Makes instructions more readable and understandable.

Add percent symbol

---

exercises/concept/vehicle-purchase/.docs/instructions.md

If I'm not mistaken, that sentence gives a wrong clue: `if the monthly payment is within 10% of your monthly budget you will want to return a special reminder to be frugal`. For me it reads that the payment may be between 0 and 10 of a 100 budget, but it is supposed to be 100 - 110.
I hope the correction is proper English: `if the monthly payment is within 10% above your monthly budget you will want to return a special reminder to be frugal`  
(Non native speaker, having a cold, brain slightly molten)

Clarify task 1 of vehicle-purchase

---

exercises/concept/vehicle-purchase/.docs/introduction.md

See https://forum.exercism.org/t/pr-to-fix-typo-in-vexing-vehicle-purchase-exercise-in-swift-track/6225/2.

fix use of assignment in guard clause

---

config.json

Based on this mermaid tree: [![](https://mermaid.ink/img/pako:eNqFVdtS4zgQ_RWVH3a0VYTKhQ0kD1tlEm4zCTA4C7ujzIMid2yBLLlkeSBD8e_btpMgWCbrh1ROt3T63noOhIkhGAaJ5XlKZuO5JvgV5aIRcDbhK7AFMUsy4QVPNP_eHKm-kB7zQorfXyXHdGR04bh2hScd0dNSCydR5UnH9JZbyRcKfOkJna1yIKHWxnH_Cuh4rt-5t2CnFkBxLcCSG-6g8Lw7pdMyW6DzOwgEu4UnqRNyC6kUCsh1aUXKC_B4zuixMcr38ZxhlLF0RnNF5NI7e8FmYDW3K2JysNwZ6yk_r6_J6l5BokfpROrpv7zVn5Xcxt9_7XvMIhAWHAkT0I6MTYmpbF2WSrU7nY7HO2HnMkkxQ1c2xt9tLbwjU3ZSCJ5XmVi-U39kGtiIq08FGZWFMxmJZKJJlJrcY7xko5RbLhwWYAfTkk15IoXkuiV1a2a51OiEx3PFQmv5agdFwiLsN_6pzujSrcg5KEy-x3HNZmWuYJcfKYuUFICh_Hxr_yu7ytcV2XFdsvV0kCkv3BvjN3QMS14qR64xHxm4146svmg7G-TqB1hleIwOeAdm9BKQMiYfzdBf2OPKSQyO3IArrSa3XJVvBuqWXmhT_sL6XTODsRT_1X8U5z1r4iNT-WSUSWTh1qH-ze5SiW4oY_JNpv6pGtpZo4izXBfLbV6-UQs8x9Z9rO6s7YUhnVSXN_CYnhpLfNFHHj3UzU0iYSyQY_M6MjXHiI …

[Config.json]: Reorder concept exercises

---

exercises/practice/acronym/.meta/Sources/Acronym/AcronymExample.swift
exercises/practice/acronym/.meta/config.json
exercises/practice/acronym/.meta/template.swift
exercises/practice/acronym/Sources/Acronym/Acronym.swift
exercises/practice/acronym/Tests/AcronymTests/AcronymTests.swift
exercises/practice/all-your-base/.meta/Sources/AllYourBase/AllYourBaseExample.swift
exercises/practice/all-your-base/.meta/template.swift
exercises/practice/all-your-base/Sources/AllYourBase/AllYourBase.swift
exercises/practice/all-your-base/Tests/AllYourBaseTests/AllYourBaseTests.swift
exercises/practice/allergies/.meta/Sources/Allergies/AllergiesExample.swift
exercises/practice/allergies/.meta/config.json
exercises/practice/allergies/.meta/template.swift
exercises/practice/allergies/.meta/tests.toml
exercises/practice/allergies/Sources/Allergies/Allergies.swift
exercises/practice/allergies/Tests/AllergiesTests/AllergiesTests.swift
exercises/practice/anagram/.meta/Sources/Anagram/AnagramExample.swift
exercises/practice/anagram/.meta/template.swift
exercises/practice/anagram/.meta/tests.toml
exercises/practice/anagram/Sources/Anagram/Anagram.swift
exercises/practice/anagram/Tests/AnagramTests/AnagramTests.swift
generator/Sources/Generator/generator-plugins.swift

This update includes:
- All your bases
- Anagram
- Allergies
- Acronym

Update exercises batch one

---

exercises/practice/diamond/.meta/Sources/Diamond/DiamondExample.swift
exercises/practice/diamond/.meta/template.swift
exercises/practice/diamond/Package.swift
exercises/practice/diamond/Sources/Diamond/Diamond.swift
exercises/practice/diamond/Tests/DiamondTests/DiamondTests.swift
exercises/practice/dominoes/.meta/Sources/Dominoes/DominoesExample.swift
exercises/practice/dominoes/.meta/config.json
exercises/practice/dominoes/.meta/template.swift
exercises/practice/dominoes/.meta/tests.toml
exercises/practice/dominoes/Package.swift
exercises/practice/dominoes/Sources/Dominoes/Dominoes.swift
exercises/practice/dominoes/Tests/DominoesTests/DominoesTests.swift
exercises/practice/flatten-array/.meta/Sources/FlattenArray/FlattenArrayExample.swift
exercises/practice/flatten-array/.meta/template.swift
exercises/practice/flatten-array/.meta/tests.toml
exercises/practice/flatten-array/Package.swift
exercises/practice/flatten-array/Sources/FlattenArray/FlattenArray.swift
exercises/practice/flatten-array/Tests/FlattenArrayTests/FlattenArrayTests.swift
exercises/practice/food-chain/.meta/Sources/FoodChain/FoodChainExample.swift
exercises/practice/food-chain/.meta/config.json
exercises/practice/food-chain/.meta/template.swift
exercises/practice/food-chain/Package.swift
exercises/practice/food-chain/Sources/FoodChain/FoodChain.swift
exercises/practice/food-chain/Tests/FoodChainTests/FoodChainTests.swift
generator/Sources/Generator/generator-plugins.swift

Includes:
- Diamond
- Dominos
- FlattenArray
- Food Chain

Updates batch 4

---

exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.meta/Sources/PigLatin/PigLatinExample.swift
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/template.swift
exercises/practice/pig-latin/Package.swift
exercises/practice/pig-latin/Sources/PigLatin/PigLatin.swift
exercises/practice/pig-latin/Tests/PigLatinTests/PigLatinTests.swift
exercises/practice/prime-factors/.meta/Sources/PrimeFactors/PrimeFactorsExample.swift
exercises/practice/prime-factors/.meta/template.swift
exercises/practice/prime-factors/Package.swift
exercises/practice/prime-factors/Sources/PrimeFactors/PrimeFactors.swift
exercises/practice/prime-factors/Tests/PrimeFactorsTests/PrimeFactorsTests.swift
exercises/practice/raindrops/.meta/Sources/Raindrops/RaindropsExample.swift
exercises/practice/raindrops/.meta/template.swift
exercises/practice/raindrops/Package.swift
exercises/practice/raindrops/Sources/Raindrops/Raindrops.swift
exercises/practice/raindrops/Tests/RaindropsTests/RaindropsTests.swift
exercises/practice/roman-numerals/.docs/instructions.append.md
exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/roman-numerals/.meta/Sources/RomanNumerals/RomanNumeralsExample.swift
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/roman-numerals/.meta/template.swift
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/Package.swift
exercises/practice/roman-numerals/Sources/RomanNumerals/RomanNumerals.swift
exercises/practice/roman-numerals/Tests/RomanNumeralsTests/RomanNumeralsTests.swift

This includes:
- Roman Numerals
- RainDrops
- PrimeFactors
- Pig-Latin

Update Exercises Batch 8

---

exercises/practice/clock/.meta/Sources/Clock/ClockExample.swift
exercises/practice/clock/.meta/template.swift
exercises/practice/clock/Package.swift
exercises/practice/clock/Sources/Clock/Clock.swift
exercises/practice/clock/Tests/ClockTests/ClockTests.swift
exercises/practice/custom-set/.meta/Sources/CustomSet/CustomSetExample.swift
exercises/practice/custom-set/.meta/template.swift
exercises/practice/custom-set/Package.swift
exercises/practice/custom-set/Sources/CustomSet/CustomSet.swift
exercises/practice/custom-set/Tests/CustomSetTests/CustomSetTests.swift
exercises/practice/rotational-cipher/.meta/Sources/RotationalCipher/RotationalCipherExample.swift
exercises/practice/rotational-cipher/.meta/template.swift
exercises/practice/rotational-cipher/Package.swift
exercises/practice/rotational-cipher/Sources/RotationalCipher/RotationalCipher.swift
exercises/practice/rotational-cipher/Tests/RotationalCipherTests/RotationalCipherTests.swift
generator/Sources/Generator/generator-plugins.swift

This includes:
- custom-set
- clock
- rotational-cipher

Update Exercises Batch 10

---

config.json
exercises/practice/bottle-song/.docs/instructions.md
exercises/practice/bottle-song/.gitignore
exercises/practice/bottle-song/.meta/Sources/BottleSong/BottleSongExample.swift
exercises/practice/bottle-song/.meta/config.json
exercises/practice/bottle-song/.meta/template.swift
exercises/practice/bottle-song/.meta/tests.toml
exercises/practice/bottle-song/Package.swift
exercises/practice/bottle-song/Sources/BottleSong/BottleSong.swift
exercises/practice/bottle-song/Tests/BottleSongTests/BottleSongTests.swift
generator/Sources/Generator/generator-help.swift

Has dependencies in: #672 
This is done to be able to  deprecate beer song

[New Exercise]: Bottle Song

---

exercises/practice/run-length-encoding/.meta/Sources/RunLengthEncoding/RunLengthEncodingExample.swift
exercises/practice/run-length-encoding/.meta/template.swift
exercises/practice/run-length-encoding/Package.swift
exercises/practice/run-length-encoding/Sources/RunLengthEncoding/RunLengthEncoding.swift
exercises/practice/run-length-encoding/Tests/RunLengthEncodingTests/RunLengthEncodingTests.swift
exercises/practice/say/.docs/instructions.md
exercises/practice/say/.meta/Sources/Say/SayExample.swift
exercises/practice/say/.meta/template.swift
exercises/practice/say/.meta/tests.toml
exercises/practice/say/Package.swift
exercises/practice/say/Sources/Say/Say.swift
exercises/practice/say/Tests/SayTests/SayTests.swift
exercises/practice/scrabble-score/.meta/Sources/ScrabbleScore/ScrabbleScoreExample.swift
exercises/practice/scrabble-score/.meta/template.swift
exercises/practice/scrabble-score/Package.swift
exercises/practice/scrabble-score/Sources/ScrabbleScore/ScrabbleScore.swift
exercises/practice/scrabble-score/Tests/ScrabbleScoreTests/ScrabbleScoreTests.swift
exercises/practice/secret-handshake/.docs/instructions.md
exercises/practice/secret-handshake/.meta/Sources/SecretHandshake/SecretHandshakeExample.swift
exercises/practice/secret-handshake/.meta/config.json
exercises/practice/secret-handshake/.meta/template.swift
exercises/practice/secret-handshake/Package.swift
exercises/practice/secret-handshake/Sources/SecretHandshake/SecretHandshake.swift
exercises/practice/secret-handshake/Tests/SecretHandshakeTests/SecretHandshakeTests.swift

This includes:
- Run Length Encoding
- Say
- Scrabble score
- Secret Handshake

Update exercises batch 11

---

exercises/practice/proverb/.meta/Sources/Proverb/ProverbExample.swift
exercises/practice/proverb/.meta/config.json
exercises/practice/proverb/.meta/template.swift
exercises/practice/proverb/Package.swift
exercises/practice/proverb/Sources/Proverb/Proverb.swift
exercises/practice/proverb/Tests/ProverbTests/ProverbTests.swift
exercises/practice/transpose/.meta/Sources/Transpose/TransposeExample.swift
exercises/practice/transpose/.meta/template.swift
exercises/practice/transpose/Package.swift
exercises/practice/transpose/Sources/Transpose/Transpose.swift
exercises/practice/transpose/Tests/TransposeTests/TransposeTests.swift
exercises/practice/triangle/.meta/Sources/Triangle/TriangleExample.swift
exercises/practice/triangle/.meta/template.swift
exercises/practice/triangle/.meta/tests.toml
exercises/practice/triangle/Package.swift
exercises/practice/triangle/Sources/Triangle/Triangle.swift
exercises/practice/triangle/Tests/TriangleTests/TriangleTests.swift
exercises/practice/word-count/.meta/Sources/WordCount/WordCountExample.swift
exercises/practice/word-count/.meta/template.swift
exercises/practice/word-count/.meta/tests.toml
exercises/practice/word-count/Package.swift
exercises/practice/word-count/Sources/WordCount/WordCount.swift
exercises/practice/word-count/Tests/WordCountTests/WordCountTests.swift

This includes:
- Proverb
- Word Count
- Transpose
- Triangle

Update exercises batch 13

---

exercises/concept/freelancer-rates/.docs/instructions.md

Based on: https://forum.exercism.org/t/exercise-improvement-suggestion/6865/1

[Free Lancer Rates]: fix incorrect instructions

---

exercises/practice/grade-school/.meta/Sources/GradeSchool/GradeSchoolExample.swift
exercises/practice/grade-school/.meta/template.swift
exercises/practice/grade-school/.meta/tests.toml
exercises/practice/grade-school/Package.swift
exercises/practice/grade-school/Sources/GradeSchool/GradeSchool.swift
exercises/practice/grade-school/Tests/GradeSchoolTests/GradeSchoolTests.swift

Update Exercises batch 14

---

exercises/practice/circular-buffer/.meta/Sources/CircularBuffer/CircularBufferExample.swift
exercises/practice/circular-buffer/.meta/template.swift
exercises/practice/circular-buffer/Package.swift
exercises/practice/circular-buffer/Sources/CircularBuffer/CircularBuffer.swift
exercises/practice/circular-buffer/Tests/CircularBufferTests/CircularBufferTests.swift
exercises/practice/house/.meta/Sources/House/HouseExample.swift
exercises/practice/house/.meta/template.swift
exercises/practice/house/Sources/House/House.swift
exercises/practice/house/Tests/HouseTests/HouseTests.swift
exercises/practice/kindergarten-garden/.meta/Sources/KindergartenGarden/KindergartenGardenExample.swift
exercises/practice/kindergarten-garden/.meta/template.swift
exercises/practice/kindergarten-garden/Package.swift
exercises/practice/kindergarten-garden/Sources/KindergartenGarden/KindergartenGarden.swift
exercises/practice/kindergarten-garden/Tests/KindergartenGardenTests/KindergartenGardenTests.swift
generator/Sources/Generator/generator-plugins.swift

This includes:
- CircularBuffer
- House
- KindergartenGarden

Update exercises batch 15

---

exercises/practice/house/Package.swift
exercises/practice/tournament/.meta/Sources/Tournament/TournamentExample.swift
exercises/practice/tournament/.meta/config.json
exercises/practice/tournament/.meta/template.swift
exercises/practice/tournament/Package.swift
exercises/practice/tournament/Sources/Tournament/Tournament.swift
exercises/practice/tournament/Tests/TournamentTests/TournamentTests.swift
exercises/practice/twelve-days/.meta/Sources/TwelveDays/TwelveDaysExample.swift
exercises/practice/twelve-days/.meta/template.swift
exercises/practice/twelve-days/Package.swift
exercises/practice/twelve-days/Sources/TwelveDays/TwelveDays.swift
exercises/practice/twelve-days/Tests/TwelveDaysTests/TwelveDaysTests.swift
exercises/practice/wordy/.meta/Sources/Wordy/WordyExample.swift
exercises/practice/wordy/.meta/template.swift
exercises/practice/wordy/Package.swift
exercises/practice/wordy/Sources/Wordy/Wordy.swift
exercises/practice/wordy/Tests/WordyTests/WordyTests.swift

This includes:
- Tournament
- Twelve-days
- Wordy

Update exercises batch 16

---

exercises/practice/pascals-triangle/.meta/Sources/PascalsTriangle/PascalsTriangleExample.swift
exercises/practice/pascals-triangle/.meta/template.swift
exercises/practice/pascals-triangle/Package.swift
exercises/practice/pascals-triangle/Sources/PascalsTriangle/PascalsTriangle.swift
exercises/practice/pascals-triangle/Tests/PascalsTriangleTests/PascalsTriangleTests.swift
exercises/practice/robot-simulator/.meta/Sources/RobotSimulator/RobotSimulatorExample.swift
exercises/practice/robot-simulator/.meta/template.swift
exercises/practice/robot-simulator/Sources/RobotSimulator/RobotSimulator.swift
exercises/practice/robot-simulator/Tests/RobotSimulatorTests/RobotSimulatorTests.swift
exercises/practice/sublist/.meta/Sources/Sublist/SublistExample.swift
exercises/practice/sublist/.meta/template.swift
exercises/practice/sublist/.meta/tests.toml
exercises/practice/sublist/Package.swift
exercises/practice/sublist/Sources/Sublist/Sublist.swift
exercises/practice/sublist/Tests/SublistTests/SublistTests.swift
generator/Sources/Generator/generator-plugins.swift

This includes:
- Pascals Triangle
- Robot Simulator
- Sublist

Update exercises batch 17

---

exercises/practice/meetup/.meta/Sources/Meetup/MeetupExample.swift
exercises/practice/meetup/.meta/template.swift
exercises/practice/meetup/Package.swift
exercises/practice/meetup/Sources/Meetup/Meetup.swift
exercises/practice/meetup/Tests/MeetupTests/MeetupTests.swift
exercises/practice/palindrome-products/.meta/Sources/PalindromeProducts/PalindromeProductsExample.swift
exercises/practice/palindrome-products/.meta/config.json
exercises/practice/palindrome-products/.meta/template.swift
exercises/practice/palindrome-products/.meta/tests.toml
exercises/practice/palindrome-products/Package.swift
exercises/practice/palindrome-products/Sources/PalindromeProducts/PalindromeProducts.swift
exercises/practice/palindrome-products/Tests/PalindromeProductsTests/PalindromeProductsTests.swift
exercises/practice/perfect-numbers/.meta/Sources/PerfectNumbers/PerfectNumbersExample.swift
exercises/practice/perfect-numbers/.meta/template.swift
exercises/practice/perfect-numbers/Package.swift
exercises/practice/perfect-numbers/Sources/PerfectNumbers/PerfectNumbers.swift
exercises/practice/perfect-numbers/Tests/PerfectNumbersTests/PerfectNumbersTests.swift
generator/Sources/Generator/generator-plugins.swift

This includes:
- Perfect Numbers
- Meet up
- Palindrome Products

Update exercises batch 18

---

exercises/practice/scale-generator/.meta/Sources/ScaleGenerator/ScaleGeneratorExample.swift
exercises/practice/scale-generator/.meta/config.json
exercises/practice/scale-generator/.meta/template.swift
exercises/practice/scale-generator/.meta/tests.toml
exercises/practice/scale-generator/Package.swift
exercises/practice/scale-generator/Sources/ScaleGenerator/ScaleGenerator.swift
exercises/practice/scale-generator/Tests/ScaleGeneratorTests/ScaleGeneratorTests.swift
exercises/practice/space-age/.docs/instructions.md
exercises/practice/space-age/.meta/Sources/SpaceAge/SpaceAgeExample.swift
exercises/practice/space-age/.meta/template.swift
exercises/practice/space-age/.meta/tests.toml
exercises/practice/space-age/Package.swift
exercises/practice/space-age/Sources/SpaceAge/SpaceAge.swift
exercises/practice/space-age/Tests/SpaceAgeTests/SpaceAgeTests.swift
exercises/practice/strain/.docs/instructions.append.md
exercises/practice/strain/.meta/Sources/Strain/StrainExample.swift
exercises/practice/strain/.meta/template.swift
exercises/practice/strain/.meta/tests.toml
exercises/practice/strain/Package.swift
exercises/practice/strain/Sources/Strain/Strain.swift
exercises/practice/strain/Tests/StrainTests/StrainTests.swift
generator/Sources/Generator/generator-plugins.swift

This includes:
- Scale Generator
- Strain
- Space Age

Update exercises batch 19

---

exercises/practice/crypto-square/.meta/Sources/CryptoSquare/CryptoSquareExample.swift
exercises/practice/crypto-square/.meta/template.swift
exercises/practice/crypto-square/.meta/tests.toml
exercises/practice/crypto-square/Package.swift
exercises/practice/crypto-square/Sources/CryptoSquare/CryptoSquare.swift
exercises/practice/crypto-square/Tests/CryptoSquareTests/CryptoSquareTests.swift
exercises/practice/queen-attack/.docs/instructions.md
exercises/practice/queen-attack/.meta/Sources/QueenAttack/QueenAttackExample.swift
exercises/practice/queen-attack/.meta/template.swift
exercises/practice/queen-attack/.meta/tests.toml
exercises/practice/queen-attack/Package.swift
exercises/practice/queen-attack/Sources/QueenAttack/QueenAttack.swift
exercises/practice/queen-attack/Tests/QueenAttackTests/QueenAttackTests.swift

This includes:
- Crypto square
- Queen attack

Update exercises batch 21

---

exercises/practice/ocr-numbers/.meta/Sources/OcrNumbers/OcrNumbersExample.swift
exercises/practice/ocr-numbers/.meta/template.swift
exercises/practice/ocr-numbers/Package.swift
exercises/practice/ocr-numbers/Sources/OcrNumbers/OcrNumbers.swift
exercises/practice/ocr-numbers/Tests/OcrNumbersTests/OcrNumbersTests.swift
exercises/practice/phone-number/.meta/Sources/PhoneNumber/PhoneNumberExample.swift
exercises/practice/phone-number/.meta/template.swift
exercises/practice/phone-number/.meta/tests.toml
exercises/practice/phone-number/Package.swift
exercises/practice/phone-number/Sources/PhoneNumber/PhoneNumber.swift
exercises/practice/phone-number/Tests/PhoneNumberTests/PhoneNumberTests.swift

This includes:
- Ocr Numbers
- Phone number

Update exercises batch 20

---

exercises/concept/master-mixologist/Tests/MasterMixologistTests/MasterMixologistTests.swift

Fix small typo in MasterMixologistTests.

Fix typo in master mixologist test

---

exercises/practice/leap/.docs/instructions.md
exercises/practice/leap/.docs/introduction.md
exercises/practice/leap/.meta/config.json

[Sync]: Leap

---

exercises/practice/saddle-points/.docs/instructions.md
exercises/practice/saddle-points/.docs/introduction.md

[Saddle points]: Sync

---

concepts/conditionals/about.md
concepts/conditionals/introduction.md
exercises/concept/vehicle-purchase/.docs/introduction.md

Fixed the values for the less than operator in the introduction to comparision operators.

Incorrect example operator

---

concepts/basics/about.md
concepts/basics/introduction.md
exercises/concept/lasagna/.docs/introduction.md

I believe a minor typo might have been introduced to this text while editing. I've edited the sentence to make it correct while maintaining what I believe was the intended meaning.

Fix a small typo in introduction.md

---

.github/workflows/configlet.yml
config.json
exercises/concept/wings-quest/.meta/config.json
exercises/practice/binary-search/.meta/config.json
exercises/practice/bottle-song/.meta/config.json
exercises/practice/reverse-string/.meta/config.json

Following on from this [comment](https://github.com/exercism/swift/pull/768#discussion_r1752980098), this fixes the formatting in the `config.json`. 
Formatting was fixed by running `configlet fmt`.
This change also adds `fmt` to the configlet github action.

Fix config.json formatting

---

config.json
exercises/practice/armstrong-numbers/.docs/instructions.md
exercises/practice/armstrong-numbers/.meta/Sources/ArmstrongNumbers/ArmstrongNumbersExample.swift
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/armstrong-numbers/.meta/template.swift
exercises/practice/armstrong-numbers/.meta/tests.toml
exercises/practice/armstrong-numbers/Package.swift
exercises/practice/armstrong-numbers/Sources/ArmstrongNumbers/ArmstrongNumbers.swift
exercises/practice/armstrong-numbers/Tests/ArmstrongNumbersTests/ArmstrongNumbersTests.swift

This exercise will test large numbers, seems like it could add a lot of complexity for this simple exercise without any real good language support for large numbers. I am considering adding this library: https://github.com/mkrd/Swift-BigInt, which would be the first library added. Since Swift doesnt have native Int128 nor bigint

[New Exercise]: Armstrong Numbers

---

.github/workflows/ci.yml
Package.swift

Update ci to be Swift 6.0 compatible.
Also add Swift Numerics for full compatibility with swift-testing

Update CI configuration and add Swift Numerics dependency

---

exercises/practice/matrix/Sources/Matrix/Matrix.swift

Remove finished solution

---

exercises/practice/clock/.meta/template.swift
exercises/practice/clock/Package.swift
exercises/practice/clock/Tests/ClockTests/ClockTests.swift
exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/collatz-conjecture/.docs/introduction.md
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/collatz-conjecture/.meta/template.swift
exercises/practice/collatz-conjecture/Package.swift
exercises/practice/collatz-conjecture/Tests/CollatzConjectureTests/CollatzConjectureTests.swift
exercises/practice/crypto-square/.meta/template.swift
exercises/practice/crypto-square/Package.swift
exercises/practice/crypto-square/Tests/CryptoSquareTests/CryptoSquareTests.swift
exercises/practice/darts/.meta/template.swift
exercises/practice/darts/Package.swift
exercises/practice/darts/Tests/DartsTests/DartsTests.swift

Includes:
- Dart
- Clock
- Crypto-square
- Collatz-conjecture

[Swift 6]: Update Exercises batch 4

---

exercises/practice/two-fer/.meta/template.swift
exercises/practice/two-fer/Package.swift
exercises/practice/two-fer/Tests/TwoFerTests/TwoFerTests.swift
exercises/practice/word-count/.meta/template.swift
exercises/practice/word-count/Package.swift
exercises/practice/word-count/Tests/WordCountTests/WordCountTests.swift
exercises/practice/wordy/.meta/template.swift
exercises/practice/wordy/Package.swift
exercises/practice/wordy/Tests/WordyTests/WordyTests.swift

Includes:
- Two-fer
- Word-count
- Wordy

[Swift 6]: Update Exercises batch 19
