exercism/swift

nucleotide-count/NucleotideCountExample.swift, nucleotide-count/NucleotideCountTest.swift
I tried to add some swift approaches to this example. 
1. The DNA should be modeled as a struct since the following apply to it.
*The structure’s primary purpose is to encapsulate a few relatively simple data values.
It is reasonable to expect that the encapsulated values will be copied rather than referenced when you assign or pass around an instance of that structure.
Any properties stored by the structure are themselves value types, which would also be expected to be copied rather than referenced.
The structure does not need to inherit properties or behavior from another existing type.*
2. The nucleobases(A,C,T,G) are enums, which is sort of self-explanatory. Nice that swift allows enums to be `Character` type.
3. The Optional Bindings `if let` made sense when converting from RawValue …
=> Use enum and struct to model nucleotide and DNA

binary/BinaryExample.swift, binary/BinaryTest.swift
https://github.com/exercism/x-common/issues/95
=> update binary to return Optionals

exercises/sum-of-multiples/SumOfMultiplesExample.swift, exercises/sum-of-multiples/SumOfMultiplesTest.swift
Require all multiples to explicitly passed in, rather than using the default value of `[3,5]`, as specified in Issue #127.
=> Remove default multiples (issue #127)

exercises/dominoes/DominoesTest.swift
Some solutions may automatically declare a singleton input to be valid
without checking it can actually be chained. This is incorrect behavior
and it is caught by this test.
Closes #131
=> dominoes: test singletons that can't be chained

exercises/clock/ClockExample.swift, exercises/clock/ClockTest.swift
Implement changes to Clock exercises and test from Issue #139.
Conformance to `comparable` is no longer required for tests and has been removed.
=> #139 Clock exercise improvements

exercises/grains/GrainsExample.swift, exercises/grains/GrainsTest.swift
Adds try/catch error handling to Grains exercise. (Partially addresses Issue #60.)
Also, improves `total` property in example by calculating it, rather than relying on the fact that it's the same as `UINT64_MAX`.
=> Add error handling to Grains exercise

config.json, exercises/all-your-base/AllYourBaseExample.swift, exercises/all-your-base/AllYourBaseTest.swift, xcodeProject/xSwift.xcodeproj/project.pbxproj
Add All Your Base exercise and deprecate Binary, Trinary, Octal, and Hexadecimal exercises.
See: https://github.com/exercism/x-common/issues/279
=> All Your Base exercise

exercises/all-your-base/AllYourBaseTest.swift, exercises/binary-search/BinarySearchTest.swift, exercises/bowling/BowlingTest.swift, exercises/grains/GrainsTest.swift, exercises/largest-series-product/LargestSeriesProductTest.swift, exercises/minesweeper/MinesweeperTest.swift, exercises/ocr-numbers/OcrNumbersTest.swift, exercises/queen-attack/QueenAttackTest.swift
Resolves #181
Use new `XCTAssertThrowsError` method to clean up tests.
=> Update to use XCTAssertThrowsError

config.json, exercises/transpose/TransposeExample.swift, exercises/transpose/TransposeTest.swift, xcodeProject/xSwift.xcodeproj/project.pbxproj
* Add Transpose exercise
In contrast with the Ruby version, the Swift version operates on arrays of `String`s, since the syntax for multi-line strings is rather cumbersome.
=> Add Transpose exercise

exercises/rna-transcription/Sources/RnaTranscriptionExample.swift, exercises/rna-transcription/Tests/RnaTranscriptionTests/RnaTranscriptionTests.swift
The failure cases defined in `canonical-data.json` were not included in the original test code.
As a result, the one complex error case failed ("ACGTXXXCTTAA") when the original code returned a truncated version of the transcription, ignoring the "XXX" middle.
I've added the tests and fixed the code. It now returns `nil` as per the spec.
=> Rna transcription fix

exercises/allergies/Tests/AllergiesTests/AllergiesTests.swift
This PR updates the [Allergies](http://exercism.io/exercises/swift/allergies/readme) exercise and adds a new unit test. This test covers one of the stated criteria: 
`Note: a given score may include allergens not listed above (i.e. allergens that score 256, 512, 1024, etc.). Your program should ignore those components of the score. For example, if the allergy score is 257, your program should only report the eggs (1) allergy.`
The test just covers the case of a score of 257.
=> Add test for other allergies

exercises/luhn/Sources/LuhnExample.swift, exercises/luhn/Tests/LinuxMain.swift, exercises/luhn/Tests/LuhnTests/LuhnTests.swift
The canonical data uses strings as input rather than ints, which required a partial rework of the example. Also, the example uses `>` where it should use `>=`, leading to a bug whenever a number contained the digit 5. I also removed an unused function from the example.
=> Rewrote tests to follow canonical data; reworked example to pass tests (fixes #232)

config.json
The previous version of `configlet uuid` was known to generate invalid UUIDs. The latest release of Configlet [v3.6.1](https://github.com/exercism/configlet/releases) fixes that issue for newly added exercises, but existing exercise UUIDs need to be updated manually.
This change pertains to exercism/configlet#99
=> config.json: Fix invalid exercise UUID

exercises/rotational-cipher/README.md
In preparation for [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) we're updating Configlet—our Exercism track linter—to require that we generate the exercise README. This is because in v2 we will not be generating READMEs on the fly, but deliver the README as defined in the directory for each implementation.
I'm going to go ahead and merge this as soon as the build passes, as this is janitorial work rather than a language-specific change.
See https://github.com/exercism/configlet/issues/116 for more details.
=> rotational-cipher: Generate missing exercise README

.travis.yml
Stop tracking swift 3.1 and start tracking changes coming to swift 4.1x
=> drop support for 3.1, add 4.1xdev

Dangerfile, exercises/collatz-conjecture/.gitignore, exercises/diamond/.gitignore, exercises/isbn-verifier/.gitignore, exercises/list-ops/.gitignore, exercises/protein-translation/.gitignore, exercises/say/.gitignore, exercises/scale-generator/.gitignore, exercises/two-fer/.gitignore
Some of the exercises are missing `.gitignore` to exclude the swift package manager generated xcodeproj. This PR adds the missing files and updates Dangerfile to check future changes if needed.
=> Add the missing .gitignore in exercises

config.json
While linting with the latest release of [Configlet](https://github.com/exercism/configlet/releases/tag/v3.8.0) the exercise `complex-numbers` was found to contain an invalid unlocked_by configuration.
The master config file was updated in the following manner:
1. Removed the unlocked_by value of `"leap"` from `complex-numbers` seeing as there are currently no core exercises defined within the track.
1. Download the latest release of Configlet [here](https://github.com/exercism/configlet/releases/tag/v3.8.0)
1. Run `configlet lint <path-to-fsharp-track>`
1. Validate that there are no lint errors.
=> config.json: Remove unlocked_by value from complex-numbers

exercises/space-age/Tests/SpaceAgeTests/SpaceAgeTests.swift
The test for space age seems to do a direct comparison of floating point numbers. I don't know swift very well at all, but with IEEE 754 floating point numbers one typically needs to compare them with a tolerance of error to account for small rounding errors introduced through arithmetic operations. This just adds such a tolerance to each of the `XCTAssertEqual` calls in the SpaceAge tests.
=> Compare floating point with tolerance in space age test.

exercises/robot-name/Tests/RobotNameTests/RobotNameTests.swift
Name format is "two uppercase letters followed by three digits".
In this patch, regex `[A-Z]{2}` tests for two upper-case ASCII letters.
Original regex `\w{2}` expands to `[a-zA-Z0-9_]{2}` which is somewhat relaxed.
Alternative regex `\\p{Lu}{2}` could accept any Unicode upper-case letter.
=> robot-name: test for upper-case letters

exercises/scale-generator/Tests/ScaleGeneratorTests/ScaleGeneratorTests.swift
This fixes the scale to 12 half steps, as in [canonical-data](https://github.com/exercism/problem-specifications/blob/c85397312197906905c295ec7d026e53159d2fd4/exercises/scale-generator/canonical-data.json#L169-L177)
=> scale-generator: fix enigmatic scale pattern

exercises/difference-of-squares/Sources/DifferenceOfSquaresExample.swift, exercises/difference-of-squares/Tests/DifferenceOfSquaresTests/DifferenceOfSquaresTests.swift
In exercise "difference-of-squares", renamed `squareOfSums` to `squareOfSum`.
=> difference-of-squares: renamed squareOfSums to squareOfSum

exercises/acronym/Sources/Acronym/AcronymExample.swift, exercises/bowling/Sources/Bowling/BowlingExample.swift, exercises/circular-buffer/Sources/CircularBuffer/CircularBufferExample.swift, exercises/flatten-array/Sources/FlattenArray/FlattenArrayExample.swift, exercises/matrix/Sources/Matrix/MatrixExample.swift, exercises/palindrome-products/Sources/PalindromeProducts/PalindromeProductsExample.swift, exercises/phone-number/Sources/PhoneNumber/PhoneNumberExample.swift, exercises/pig-latin/Sources/PigLatin/PigLatinExample.swift, exercises/poker/Sources/Poker/PokerExample.swift, exercises/simple-cipher/Tests/SimpleCipherTests/SimpleCipherTests.swift
These warnings were missed in my initial Swift 4.2 migration PR.
=> Fix remaining warnings after upgrading to Swift 4.2

exercises/twelve-days/Sources/TwelveDays/TwelveDaysExample.swift, exercises/twelve-days/Tests/TwelveDaysTests/TwelveDaysTests.swift
* Fixes issue #370 by matching tests to new specification
* Use multi-line string literals (not available when originally written)
* Improve example solution with a more efficient one
=> Revise Twelve Days exercise

docs/TESTS.md
* Update language to be more "newbie" friendly. E.g. change "execute" to "type xyz and press enter"
* Add instructions for how to open an xcode project
* Add a section at the top to guide new users to the relevant sections, as they are easy to miss when scanning then page
=> Provide more newbie friendly instructions

exercises/practice/hello-world/Sources/HelloWorld/HelloWorld.swift, exercises/practice/hello-world/Sources/HelloWorld/HelloWorldExample.swift, exercises/practice/hello-world/Tests/HelloWorldTests/HelloWorldTests.swift
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

config.json, exercises/concept/santas-helper/.meta/design.md
This fixes some prerequisites of concept exercises that point to concepts that do not exist (yet). Specifically, the following non-existing concepts were prerequisites for other exercises:
- `strings` (should probably be `characters` instead)
- `conditionals` (covered by `conditionals-if`, `conditionals-guard` and `conditionals-switch`)
Because of these incorrect prerequisites some exercises remain locked without a way to unlock them.
Note: An alternative fix for `conditionals` could be to add the `conditionals` concept to the appropriate exercises instead of changing the prerequisites of the others.
=> Fix prerequisites of concept exercises

exercises/concept/log-lines/.docs/instructions.md
Point 2 mentions `LogLine` but it should be `LogLevel`.
> Next, implement the LogLevel initializer to parse the log level of a log line:
> 
> ```
> LogLevel("[INF]: File deleted")
> // => LogLevel.info
> LogLevel("Something went wrong!")
> // => LogLevel.unknown
> ```
=> Log Lines : fix LogLine by LogLevel in instructions

exercises/concept/windowing-system/.docs/instructions.md, exercises/concept/windowing-system/Tests/WindowingSystemTests/WindowingSystemTests.swift
Point 1 states to implement `resize(newHeight:newWidth:)` but tests are using `resize(newWidth:newHeight:)`.
Per convention `width` should go before `height`.
=> Windowing System : changed instructions' Size width and height to make them fit tests.

exercises/concept/vehicle-purchase/Tests/VehiclePurchaseTests/VehiclePurchaseTests.swift
I found a typo while solving the exercise, "Veryon" should be "Veyron".
=> Fix typo in vehicle-purchase exercise tests

exercises/concept/lasagna-master/.meta/Sources/LasagnaMaster/LasagnaMasterExemplar.swift, exercises/concept/lasagna-master/Tests/LasagnaMasterTests/LasagnaMasterTests.swift
From the instructions:
> You've heard that you should serve white wine if there is more mozzarella, ricotta, and béchamel in the lasagna than there is meat and sauce, and red wine otherwise.
Let's call the number of mozzarella/ricotta/béchamel layers `A` and the number of meat/sauce layers `B`: according to the instructions white wine should be served when `A > B`, which means that the `redWine` function should return `true` when `A <= B`, not `A < B`. 
However, in the test case `A == B`, which means that the test fails if a student implements the `redWine` function to return `true` when `A <= B`. To fix this, I added an extra `"mozzarella"` layer to the test case, so that it represents the case `A > B` and therefore correctly expects `false`.
=> lasagna-master: Update tests of final task to match instructions

exercises/concept/high-score-board/.docs/introduction.md
var emptyDict2 = ["Character": "String"]() generates an error.
Correct declaration of empty dictionary is:
var emptyDict2 = [Character: String]()
=> Improved bad example in high-score-board introduction

exercises/concept/windowing-system/.docs/instructions.md
Instruction "The initial width and height should be 60 and 80, respectively." is wrong. It should be: "80 and 60, respectively." Users are loosing a lot of time because that error in instruction.
=> Correction in first exercise

concepts/characters/introduction.md
There is an extra full stop in the second one, which led me to believe that that comparison was correct. I researched it and it is not. Here is a fix for it!
=> [Characters Concept] Fix typo with full stop

exercises/concept/vehicle-purchase/.docs/instructions.md, exercises/concept/vehicle-purchase/.docs/introduction.md
Proposed fixes for:
`licence` to `license` in
```licenceType(numberOfWheels: 0)```
`she` to `such` in
I.e. it must use a control transfer statement she as return, continue, break, or it must throw an error or exit the program.
=> Fix typos in instructions.md and introduction.md

exercises/concept/magician-in-training/.docs/instructions.md, exercises/concept/magician-in-training/.docs/introduction.md
Proposed fixes for:
`the` to `they` in
"arrays to see if the are empty before"
`3` to `4`
evenCardCount([3,8,4,5,1,6,10]) // There are 4 even numbers (not 3)
// => 3  <--- Here
=> Magician-in-Training: Fix typos in instructions.md and introduction.md

config.json
This resolves the following issue:
```
`/home/runner/work/swift/swift/concepts` contains a directory named `constants-and-variables`, which is not a `slug` in the concepts array. Please add the concept to that array:
/home/runner/work/swift/swift/config.json
```
Can be seen here: https://github.com/exercism/swift/runs/4304703883?check_suite_focus=true
This may also relate to issue: https://github.com/exercism/swift/issues/476
=> Fix ci linter issue for missing slug

exercises/concept/custom-signs/.docs/instructions.md
fix text at step 4 description where is expected a `Int` type for `year` parameter instead of `string` type.
=> fix instruction 4 parameter type

concepts/dictionaries/introduction.md
```swift
var emptyDict2 = ["Character": "String"]()
```
This declaration will not compile as there is key and value provided, not the types of the Dictionary.
The correct form should look like this:
=> Fixed typo in dict2 declaration

exercises/concept/bomb-defuser/.docs/instructions.md
tiny bit to match the rest of the doc
=> Change rotator to `rotator`

exercises/concept/freelancer-rates/.docs/instructions.md, exercises/concept/freelancer-rates/.docs/introduction.md, exercises/concept/vehicle-purchase/.docs/introduction.md
I found some typo issue during solving the exercise.
It would be nice to merge this PR for someone would get confused when they see it.
=> fix miss typo on instructions.md and introduction.md

exercises/concept/magician-in-training/Tests/MagicianInTrainingTests/MagicianInTrainingTests.swift
Change var to let as let unless it shows error `Cannot assign through subscript: 'stack' is a 'let' constant`
=> Update testSetCard in MagicianInTraining Unit Test

exercises/concept/magician-in-training/Tests/MagicianInTrainingTests/MagicianInTrainingTests.swift
Reverts exercism/swift#559
I'm sorry, I think I've made a mistake that appeared in the test from my last PR
As I didn't think about returning new arrays, as the parameter of a function is a constant...
Can you please revert the changes?
```
/mnt/exercism-iteration/Tests/MagicianInTrainingTests/MagicianInTrainingTests.swift:16:9: warning: variable 'stack' was never mutated; consider changing to 'let' constant
var stack = [9, 4, 3, 6, 1, 7, 2, 8, 5]
~~~ ^
let
/mnt/exercism-iteration/Tests/MagicianInTrainingTests/MagicianInTrainingTests.swift:23:9: warning: variable 'stack' was never mutated; consider changing to 'let' constant
var stack = [9, 4, 3, 6, 1, 7, 2, 8, 5]
~~~ ^
let
/mnt/exercism-iteration/Tests/MagicianInTrainingTests/MagicianInTrainingTests.swift:30:9: warning: variable 'stack' …
```
=> Revert "Update testSetCard in MagicianInTraining Unit Test"

docs/TESTS.md
Fixes #373 
Tested locally in my browser. Should also work in production because the same fix (exercism/delphi#260) worked for the [Delphi track docs](https://exercism.io/tracks/delphi/installation).
=> Fix broken image links in TESTS.md

concepts/arrays/links.json, concepts/default-parameters/about.md, concepts/function-overloading/links.json, concepts/functions/about.md, concepts/importing/about.md, concepts/inout-parameters/about.md, concepts/loops/links.json, concepts/multiple-return-values/about.md, concepts/nested-functions/about.md, concepts/numbers/about.md, concepts/variadic-parameters/about.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/TESTS.md
=> Updated concept docs and the docs

exercises/practice/gigasecond/.docs/hints.md
Foundation is required for time and date functions; this had me a little confused for a long time. Due to the time at which this practice is made available, there should be a hint of it.
=> hint at Foundation

exercises/practice/gigasecond/Sources/Gigasecond/Gigasecond.swift
This will help to avoid needing to inspect the tests in order to understand the expected names and structures. It should be edited by a maintainer to better fit if needed.
=> Explicit expectations

exercises/concept/poetry-club/.docs/instructions.md
This changes to use one sentence per line, and use 1. for all numbered list items.
I'm redoing #516 which is failing CI, giving credit to @kotp.
Closes #516
=> Update poetry-club instructions per markdown spec

exercises/practice/largest-series-product/Tests/LargestSeriesProductTests/LargestSeriesProductTests.swift
We deleted a couple of tests from the test suite
but they were still being referenced from allTests.
This deletes the stray references.
=> Fix largest-series-products tests

concepts/arrays/introduction.md
Fixed a typo in the introduction of `Array`.
=> Fix Typo 'the are' -> 'they are'

docs/SNIPPET.txt
This is done because:
- The snippet isn't fully visible on the website, this will likely not fix it but hopefully improve it
- Since the track is moving to 2 indented
=> Use 2 indented snippet

concepts/basics/about.md, concepts/basics/introduction.md, exercises/concept/lasagna/.docs/introduction.md
Hello, I believe that "most" in the sentence "When a function has a return type most be sure to return a value of that type." is not supposed to be there. Sorry in advance if I misunderstood it somehow 😇
=> Fixed leftover word in concepts/basics

exercises/concept/lasagna/Tests/LasagnaTests/LasagnaTests.swift
The default value for `runAll` was changed to true which makes all tests run by default, and the comments to change true to false incorrect. Changing it to false also makes it consistent with unit tests in other exercises (at least the 4 I checked).
=> Update default value for runAll variable in tests

exercises/concept/freelancer-rates/.docs/instructions.md
Prior to rounding the `monthlyRateFrom()` function should have a value of `12601.6` given the values in the test...
https://github.com/exercism/swift/blob/19b3d8f6afdb5f34629a55bf80e8ffa4e079c87c/exercises/concept/freelancer-rates/Tests/FreelancerRatesTests/FreelancerRatesTests.swift#L34C13-L37
If, (as the instructions say) this value is rounded down the result would be `12601.0` not the expected `12602.0`.
=> Fixed the rounding instructions for `monthlyRateFrom()` function.

exercises/concept/high-score-board/Sources/HighScoreBoard/HighScoreBoard.swift
There are a few function names that are incorrect in `HighScoreBoard.swift`. This PR just fixes those.
=> Fixed not implemented error messages in HighScoreBoard.swift

concepts/basics/about.md, concepts/basics/introduction.md, concepts/booleans/about.md, concepts/booleans/introduction.md, concepts/numbers/about.md, concepts/numbers/introduction.md, exercises/concept/freelancer-rates/.docs/introduction.md, exercises/concept/lasagna/.docs/introduction.md, exercises/concept/wings-quest/.docs/introduction.md, exercises/practice/linked-list/.docs/instructions.md
In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705
=> Convert backtick (`) admonition fences to tildes (~)

concepts/dictionaries/introduction.md
Corrected a grammatical error in the documentation by replacing 'on' with 'one' to improve clarity and correctness.
=> "Fixed a typo in the documentation."

concepts/basics/about.md, concepts/basics/introduction.md, exercises/concept/lasagna/.docs/introduction.md
What this fixes:
- Issues/improvements raised in issue #728:
- Two sentences that seem to say the same thing (drawing the distinction between explicit type annotation and implicit typing by the compiled)
- Spelling errors
- Possible misuse of 'parse' for 'pass'?
- Transposition of words (`s/are functions/functions are/`)
Related issue: #728
=> [Documentation] (Issue 728) Fix/improve Lasagna introduction.md

concepts/dictionaries/about.md, exercises/concept/high-score-board/.docs/introduction.md
In this PR I propose to fix a small typo in the high-score board instructions file.
Let me know if you would prefer to group this fix with other fixes. I haven't spotted others so far. I see that https://github.com/exercism/swift/pull/725 is still open, so maybe they can be grouped.
=> Fix typo in high-score board instructions

config.json, exercises/practice/knapsack/.docs/instructions.append.md, exercises/practice/knapsack/.docs/instructions.md, exercises/practice/knapsack/.docs/introduction.md, exercises/practice/knapsack/.meta/Sources/Knapsack/Item.swift, exercises/practice/knapsack/.meta/Sources/Knapsack/KnapsackExample.swift, exercises/practice/knapsack/.meta/config.json, exercises/practice/knapsack/.meta/template.swift, exercises/practice/knapsack/.meta/tests.toml, exercises/practice/knapsack/Package.swift, exercises/practice/knapsack/Sources/Knapsack/Item.swift, exercises/practice/knapsack/Sources/Knapsack/Knapsack.swift, exercises/practice/knapsack/Tests/KnapsackTests/KnapsackTests.swift, generator/Sources/Generator/generator-plugins.swift
This is one of the [48in24](https://forum.exercism.org/t/48in24-exercise-08-13-knapsack/12054) exercises.
=> Add Knapsack exercise

concepts/dictionaries/about.md, concepts/dictionaries/introduction.md, exercises/concept/high-score-board/.docs/introduction.md
=> Fix avogadro constant typo

concepts/enumerations/about.md, concepts/enumerations/introduction.md, exercises/concept/log-lines/.docs/introduction.md
Just a little typo in the enum name.
=> Fix `NESButtons` typo

exercises/concept/vehicle-purchase/.docs/instructions.md
=> Update vehicle purchase instructions to be more clear

concepts/conditionals/about.md, concepts/conditionals/introduction.md, exercises/concept/vehicle-purchase/.docs/introduction.md
=> Fix typo in constant declaration

exercises/practice/acronym/.meta/template.swift, exercises/practice/acronym/Package.swift, exercises/practice/acronym/Tests/AcronymTests/AcronymTests.swift, exercises/practice/all-your-base/.meta/template.swift, exercises/practice/all-your-base/Package.swift, exercises/practice/all-your-base/Tests/AllYourBaseTests/AllYourBaseTests.swift
Include:
- Acronym
- All-your-base
=> [Swift 6]: Update Exercises batch 1

exercises/practice/allergies/.meta/template.swift, exercises/practice/allergies/Package.swift, exercises/practice/allergies/Tests/AllergiesTests/AllergiesTests.swift, exercises/practice/anagram/.meta/template.swift, exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/Package.swift, exercises/practice/anagram/Tests/AnagramTests/AnagramTests.swift, exercises/practice/atbash-cipher/.docs/instructions.md, exercises/practice/atbash-cipher/.meta/config.json, exercises/practice/atbash-cipher/.meta/template.swift, exercises/practice/atbash-cipher/Package.swift, exercises/practice/atbash-cipher/Tests/AtbashCipherTests/AtbashCipherTests.swift, exercises/practice/binary-search/.meta/template.swift, exercises/practice/binary-search/Package.swift, exercises/practice/binary-search/Tests/BinarySearchTests/BinarySearchTests.swift
Included:
- Binary-search
- Atbash-cipher
- Anagram
- Allergies
=> [Swift 6]: Update Exercises batch 2

exercises/practice/diamond/.meta/template.swift, exercises/practice/diamond/Package.swift, exercises/practice/diamond/Tests/DiamondTests/DiamondTests.swift, exercises/practice/difference-of-squares/.meta/template.swift, exercises/practice/difference-of-squares/Package.swift, exercises/practice/difference-of-squares/Tests/DifferenceOfSquaresTests/DifferenceOfSquaresTests.swift, exercises/practice/dominoes/.meta/template.swift, exercises/practice/dominoes/Package.swift, exercises/practice/dominoes/Tests/DominoesTests/DominoesTests.swift, exercises/practice/etl/.meta/template.swift, exercises/practice/etl/Package.swift, exercises/practice/etl/Tests/EtlTests/EtlTests.swift
Includes:
- Etl
- Diamonds
- Dominoes
- Difference of squares
=> [Swift 6]: Update Exercises batch 5

exercises/practice/largest-series-product/.meta/template.swift, exercises/practice/largest-series-product/Package.swift, exercises/practice/largest-series-product/Tests/LargestSeriesProductTests/LargestSeriesProductTests.swift, exercises/practice/leap/.meta/template.swift, exercises/practice/leap/Package.swift, exercises/practice/leap/Tests/LeapTests/LeapTests.swift, exercises/practice/luhn/.meta/template.swift, exercises/practice/luhn/Package.swift, exercises/practice/luhn/Tests/LuhnTests/LuhnTests.swift, exercises/practice/matching-brackets/.meta/template.swift, exercises/practice/matching-brackets/Package.swift, exercises/practice/matching-brackets/Tests/MatchingBracketsTests/MatchingBracketsTests.swift
Includes:
- Largest-series-product
- Leap
- Luhn
- Matching-brackets
=> [Swift 6]: Update Exercises batch 9

exercises/practice/matrix/.meta/template.swift, exercises/practice/matrix/Package.swift, exercises/practice/matrix/Tests/MatrixTests/MatrixTests.swift, exercises/practice/meetup/.meta/template.swift, exercises/practice/meetup/Package.swift, exercises/practice/meetup/Tests/MeetupTests/MeetupTests.swift, exercises/practice/minesweeper/.meta/template.swift, exercises/practice/minesweeper/Package.swift, exercises/practice/minesweeper/Tests/MinesweeperTests/MinesweeperTests.swift, exercises/practice/nth-prime/.meta/template.swift, exercises/practice/nth-prime/Package.swift, exercises/practice/nth-prime/Tests/NthPrimeTests/NthPrimeTests.swift
Includes:
- Matrix
- Meetup
- Minesweeper
- Nth-prime
=> [Swift 6]: Update Exercises batch 10

exercises/practice/raindrops/.meta/template.swift, exercises/practice/raindrops/Package.swift, exercises/practice/raindrops/Tests/RaindropsTests/RaindropsTests.swift, exercises/practice/reverse-string/.meta/template.swift, exercises/practice/reverse-string/.meta/tests.toml, exercises/practice/reverse-string/Package.swift, exercises/practice/reverse-string/Tests/ReverseStringTests/ReverseStringTests.swift, exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/rna-transcription/.meta/template.swift, exercises/practice/rna-transcription/Package.swift, exercises/practice/rna-transcription/Tests/RnaTranscriptionTests/RnaTranscriptionTests.swift, exercises/practice/robot-simulator/.meta/template.swift, exercises/practice/robot-simulator/Package.swift, exercises/practice/robot-simulator/Tests/RobotSimulatorTests/RobotSimulatorTests.swift
Includes:
- Raindrops
- Reverse-string
- Rna-transcription
- Robot-simulator
=> [Swift 6]: Update Exercises batch 14

exercises/practice/scrabble-score/.meta/template.swift, exercises/practice/scrabble-score/Package.swift, exercises/practice/scrabble-score/Tests/ScrabbleScoreTests/ScrabbleScoreTests.swift, exercises/practice/secret-handshake/.meta/template.swift, exercises/practice/secret-handshake/Package.swift, exercises/practice/secret-handshake/Tests/SecretHandshakeTests/SecretHandshakeTests.swift, exercises/practice/series/.meta/template.swift, exercises/practice/series/Package.swift, exercises/practice/series/Tests/SeriesTests/SeriesTests.swift, exercises/practice/sieve/.meta/template.swift, exercises/practice/sieve/Package.swift, exercises/practice/sieve/Tests/SieveTests/SieveTests.swift
Includes:
- Scrabble-score
- Secret-handshake
- Series
- Sieve
=> [Swift 6]: Update Exercises batch 16

config.json, exercises/practice/scale-generator/.meta/template.swift, exercises/practice/scale-generator/Package.swift, exercises/practice/scale-generator/Tests/ScaleGeneratorTests/ScaleGeneratorTests.swift
Move deprecated exercises to the end.
Mark `accumulate` and `scale-generator` as depricated.
Scale generator will be updated to be compatible with 6.0.
=> [Swift 6] Depricate exercises

exercises/practice/robot-name/.meta/Sources/RobotName/RobotNameExample.swift, exercises/practice/robot-name/Package.swift, exercises/practice/robot-name/Tests/RobotNameTests/RobotNameTests.swift, exercises/practice/simple-linked-list/.meta/Sources/SimpleLinkedList/SimpleLinkedListExample.swift, exercises/practice/simple-linked-list/Package.swift, exercises/practice/simple-linked-list/Tests/SimpleLinkedListTests/SimpleLinkedListTests.swift
Includes:
- Simple-linked-list
- Robot-name
=> [Swift 6]: Update Exercises batch 21

exercises/concept/freelancer-rates/Package.swift, exercises/concept/freelancer-rates/Tests/FreelancerRatesTests/FreelancerRatesTests.swift, exercises/concept/lasagna-master/Package.swift, exercises/concept/lasagna-master/Tests/LasagnaMasterTests/LasagnaMasterTests.swift, exercises/concept/pizza-slices/Package.swift, exercises/concept/pizza-slices/Tests/PizzaSlicesTests/PizzaSlicesTests.swift, exercises/practice/complex-numbers/.docs/instructions.append.md, exercises/practice/complex-numbers/.meta/Sources/ComplexNumbers/ComplexNumbersExample.swift, exercises/practice/complex-numbers/Package.swift, exercises/practice/space-age/.meta/template.swift, exercises/practice/space-age/Package.swift, exercises/practice/space-age/Tests/SpaceAgeTests/SpaceAgeTests.swift
While doing preformance tests: https://github.com/exercism/swift-test-runner/pull/59
I did both some optimzation on the test runners logic itself but I also found that the library needed could be made smaller. This is a pr to test if that could make the preformance to an acceptable level.
=> Swift-Numerics try to improve preformance

exercises/concept/chessboard/.meta/Sources/Chessboard/ChessboardExemplar.swift, exercises/concept/chessboard/Sources/Chessboard/Chessboard.swift, exercises/concept/chessboard/Tests/ChessboardTests/ChessboardTests.swift
A function name was invalid in an error message. Also, a repeated typo was fixed.
=> fix : chessboard test and template issues

concepts/for-loops/about.md, concepts/for-loops/introduction.md, exercises/concept/bird-watcher/.docs/introduction.md, exercises/concept/bird-watcher/Sources/BirdWatcher/BirdWatcher.swift
All changes are fully backward compatible.
So we can add `[no important files changed]` to merge-commit message.
=> fix: birdwatcher template and document issues

Package.swift, exercises/practice/diamond/.meta/Sources/Diamond/DiamondExample.swift, exercises/practice/grade-school/.meta/Sources/GradeSchool/GradeSchoolExample.swift, exercises/practice/kindergarten-garden/.meta/Sources/KindergartenGarden/KindergartenGardenExample.swift, exercises/practice/roman-numerals/.meta/Sources/RomanNumerals/RomanNumeralsExample.swift, exercises/practice/saddle-points/.meta/Sources/SaddlePoints/SaddlePointsExample.swift, exercises/practice/sum-of-multiples/.meta/Sources/SumOfMultiples/SumOfMultiplesExample.swift
The Swift compiler has complained about these codesnipets, both for consistency and correctness, and due to some functions used are deprecated.
=> fix: update various code snippets for consistency and correctness

config.json, exercises/practice/resistor-color/.docs/instructions.md, exercises/practice/resistor-color/.meta/Sources/ResistorColor/ResistorColorExample.swift, exercises/practice/resistor-color/.meta/config.json, exercises/practice/resistor-color/.meta/template.swift, exercises/practice/resistor-color/.meta/tests.toml, exercises/practice/resistor-color/Package.swift, exercises/practice/resistor-color/Sources/ResistorColor/ResistorColor.swift, exercises/practice/resistor-color/Tests/ResistorColorTests/ResistorColorTests.swift
First try to add practise exercise from [list](https://exercism.org/tracks/swift/build).
=> [New Exercise]: Resistor color

exercises/practice/queen-attack/.meta/template.swift, exercises/practice/queen-attack/Tests/QueenAttackTests/QueenAttackTests.swift
During [the mentoring session](https://exercism.org/mentoring/discussions/67db264d34554cc795402ca295072b18) I've figured out that there is a problem with running tests in CI for [Queen Attack](https://github.com/exercism/swift/tree/main/exercises/practice/queen-attack) exercise.
Looks like test are passing, but for some reason test results are not passed to external artifacts.
```
Build complete! (11.16s)
Test Suite 'All tests' started at 2025-06-18 19:55:45.422
Test Suite 'debug.xctest' started at 2025-06-18 19:55:45.423
Test Suite 'QueenAttackTests' started at 2025-06-18 19:55:45.423
Test Case 'QueenAttackTests.testCanAttackOnFirstDiagonal' started at 2025-06-18 19:55:45.423
...
...
19:55:45.525	 Executed 13 tests, with 0 failures (0 unexpected) in 0.102 (0.102) seconds
Test Suite …
```
=> Rewrite test template for Queen-Attack practise exercise to wotk with Swift Testing

.github/workflows/ci.yml
Due to the Ubuntu ci have a tendency to fail (this is due to a dependency which has this as known issue). It is intended to be solved with the next version which seems to be stalled atm. So I decide to disable them for now.
=> Remove Ubuntu from CI workflow, using only macOS for testing

.github/workflows/ci.yml
Swift 6 ci is now also broken (Ubuntu was broken and removed). I would suppose that this is caused by the underlying macos image changed which caused it to fail. For now the easiest fix is just removing the ci.
=> Remove Swift 6.0 from CI matrix, keeping only Swift 6.1
